image:
  repository: giolekva/pcloud-installer
  tag: latest
  pullPolicy: Always
repoAddr: 192.168.0.11
sshPrivateKey: key
ingress:
  className: example-ingress-private
  domain: apps.p.example.com
  certificateIssuer: example-private
clusterRoleName: example-welcome
appRepoAddr: ""
