annotations:
  artifacthub.io/license: GPL-3.0-only
  artifacthub.io/links: |
    - name: Homepage
      url: https://www.openproject.org/
    - name: OpenProject Community
      url: https://community.openproject.org
    - name: support
      url: https://www.openproject.org/docs/development/report-a-bug/
  artifacthub.io/signKey: |
    fingerprint: CB1CA0488A75B7471EA1B087CF56DD6A0AE260E5
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/CB1CA0488A75B7471EA1B087CF56DD6A0AE260E5
apiVersion: v2
appVersion: "13"
dependencies:
- condition: postgresql.bundled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: ^12.1.6
- condition: memcached.bundled
  name: memcached
  repository: https://charts.bitnami.com/bitnami
  version: ^6.3.2
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: ^2.2.2
description: A Helm chart for running OpenProject via Kubernetes
home: https://www.openproject.org/
icon: https://charts.openproject.org/logo.svg
maintainers:
- name: OpenProject
  url: https://github.com/opf/helm-charts
name: openproject
type: application
version: 5.1.3
