replicaCount: 1

storageClass:
  create: true
  defaultClass: false
  # The name of the StorageClass has to be the same as the one defined in the
  # gerrit chart for `storageClasses.shared.name`
  name: shared-storage
  parameters:
    # Required!
    mountOptions: vers=4.1
  reclaimPolicy: Delete

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 100m
    memory: 256Mi
